<?php

declare(strict_types=1);

namespace PackageVersions;

use Composer\InstalledVersions;
use OutOfBoundsException;

class_exists(InstalledVersions::class);

/**
 * This class is generated by composer/package-versions-deprecated, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 *
 * @deprecated in favor of the Composer\InstalledVersions class provided by Composer 2. Require composer-runtime-api:^2 to ensure it is present.
 */
final class Versions
{
    /**
     * @deprecated please use {@see self::rootPackageName()} instead.
     *             This constant will be removed in version 2.0.0.
     */
    const ROOT_PACKAGE_NAME = 'taste/dev';

    /**
     * Array of all available composer packages.
     * Dont read this array from your calling code, but use the \PackageVersions\Versions::getVersion() method instead.
     *
     * @var array<string, string>
     * @internal
     */
    const VERSIONS          = array (
  'aferrandini/phpqrcode' => '1.0.1@3c1c0454d43710ab5bbe19a51ad4cb41c22e3d46',
  'behat/transliterator' => 'v1.5.0@baac5873bac3749887d28ab68e2f74db3a4408af',
  'chillerlan/php-qrcode' => '3.4.1@468603b687a5fe75c1ff33857a45f1726c7b95a9',
  'chillerlan/php-settings-container' => '1.2.2@d1b5284d6eb3a767459738bb0b20073f0cb3eeaf',
  'cocur/slugify' => 'v2.5@e8167e9a3236044afebd6e8ab13ebeb3ec9ca145',
  'composer/package-versions-deprecated' => '1.11.99.5@b4f54f74ef3453349c24a845d22392cd31e65f1d',
  'deployer/deployer' => 'v4.3.4@8fc00d4877b7d15c385cba4cf0eef4e78c4e9b75',
  'doctrine/annotations' => '1.14.3@fb0d71a7393298a7b232cbf4c8b1f73f3ec3d5af',
  'doctrine/cache' => '1.13.0@56cd022adb5514472cb144c087393c1821911d09',
  'doctrine/collections' => '1.8.0@2b44dd4cbca8b5744327de78bafef5945c7e7b5e',
  'doctrine/common' => '2.13.3@f3812c026e557892c34ef37f6ab808a6b567da7f',
  'doctrine/data-fixtures' => '1.5.4@d25660094fb25ee139aac11c7f052bea169b3f88',
  'doctrine/dbal' => '2.13.9@c480849ca3ad6706a39c970cdfe6888fa8a058b8',
  'doctrine/deprecations' => 'v1.0.0@0e2a4f1f8cdfc7a92ec3b01c9334898c806b30de',
  'doctrine/doctrine-bundle' => '1.12.13@85460b85edd8f61a16ad311e7ffc5d255d3c937c',
  'doctrine/doctrine-cache-bundle' => '1.4.0@6bee2f9b339847e8a984427353670bad4e7bdccb',
  'doctrine/doctrine-fixtures-bundle' => 'v2.4.1@74b8cc70a4a25b774628ee59f4cdf3623a146273',
  'doctrine/event-manager' => '1.2.0@95aa4cb529f1e96576f3fda9f5705ada4056a520',
  'doctrine/inflector' => '1.4.4@4bd5c1cdfcd00e9e2d8c484f79150f67e5d355d9',
  'doctrine/instantiator' => '1.5.0@0a0fa9780f5d4e507415a065172d26a98d02047b',
  'doctrine/lexer' => '1.2.3@c268e882d4dbdd85e36e4ad69e02dc284f89d229',
  'doctrine/orm' => '2.7.5@01187c9260cd085529ddd1273665217cae659640',
  'doctrine/persistence' => '1.3.8@7a6eac9fb6f61bba91328f15aa7547f4806ca288',
  'doctrine/reflection' => '1.2.3@1034e5e71f89978b80f9c1570e7226f6c3b9b6fb',
  'dompdf/dompdf' => 'v2.0.3@e8d2d5e37e8b0b30f0732a011295ab80680d7e85',
  'elfet/pure' => 'v3.0.0@05aa6b44cea9b0457ec1e5e67e8278cd89d47f21',
  'evenement/evenement' => 'v2.1.0@6ba9a777870ab49f417e703229d53931ed40fd7a',
  'ezyang/htmlpurifier' => 'v4.16.0@523407fb06eb9e5f3d59889b3978d5bfe94299c8',
  'fig/link-util' => '1.1.2@5d7b8d04ed3393b4b59968ca1e906fb7186d81e8',
  'fresh/vich-uploader-serialization-bundle' => 'v2.4.3@21d988723c39bd6384865ca5c764a4446cedbcbc',
  'friendsofsymfony/jsrouting-bundle' => '1.6.3@49c1069132dcef371fb526351569deabeb6f0d8e',
  'friendsofsymfony/user-bundle' => 'v2.0.2@2fc8a023d7ab482321cf7ec810ed49eab40eb50f',
  'gedmo/doctrine-extensions' => 'v2.4.42@b6c4442b4f32ce05673fbdf1fa4a2d5e315cc0a4',
  'gregwar/captcha' => 'v1.2.0@6e5b61b66ac89885b505153f4ef9a74ffa5b3074',
  'gregwar/captcha-bundle' => 'v2.0.7@3ccfdf1c9324acbdfbcccea2c454075115741b3a',
  'guzzle/parser' => 'v3.9.2@6874d171318a8e93eb6d224cf85e4678490b625c',
  'guzzlehttp/guzzle' => '7.5.0@b50a2a1251152e43f6a37f0fa053e730a67d25ba',
  'guzzlehttp/promises' => '1.5.2@b94b2807d85443f9719887892882d0329d1e2598',
  'guzzlehttp/psr7' => '2.4.4@3cf1b6d4f0c820a2cf8bcaec39fc698f3443b5cf',
  'imagine/imagine' => 'v0.7.1@a9a702a946073cbca166718f1b02a1e72d742daa',
  'incenteev/composer-parameter-handler' => 'v2.1.5@e1dd118763503f7fd766f907013e1d76d525fcc4',
  'ip/slugify-namer' => '1.1.0@d7b46fc7ed897216d6a8e7b1e7c0ca158c60bbc1',
  'irongit/symfony2-stream-response' => 'dev-master@3e5082e7beec9c9130e30e49bad44e1e99ab33b1',
  'jdorn/sql-formatter' => 'v1.2.17@64990d96e0959dff8e059dfcdc1af130728d92bc',
  'jms/aop-bundle' => '1.3.0@4ee2089a81b54ce94a8c94e95b48d5bb353dd8d0',
  'jms/cg' => '1.2.0@2152ea2c48f746a676debb841644ae64cae27835',
  'jms/di-extra-bundle' => '1.9.2@fa82a4e6c9dc84df8015805028575217c0be4a54',
  'jms/i18n-routing-bundle' => '2.0.4@052917faa3f00801c288f6d475ef7e2485928d5b',
  'jms/metadata' => '1.7.0@e5854ab1aa643623dc64adde718a8eec32b957a8',
  'jms/parser-lib' => '1.0.1@4f45952f9fa97d67adc5dd69e7d622fc89a7675d',
  'jms/serializer' => '1.14.1@ba908d278fff27ec01fb4349f372634ffcd697c0',
  'jms/serializer-bundle' => '2.4.4@92ee808c64c1c180775a0e57d00e3be0674668fb',
  'jms/translation-bundle' => '1.7.0@153f4c9892bd6481eebd42c5da56666c8d0fa7ce',
  'kachkaev/php-r' => 'dev-master@8aa5bb42e6042cef1a4ab12b63782f4d17ce0f1d',
  'knplabs/knp-menu' => '2.6.1@56ffccc3ed8f7b69ec6e6d587e9f840c0a270739',
  'knplabs/knp-menu-bundle' => 'v2.3.0@78b0cebf8e1490f12ba6555511282954de83f627',
  'knplabs/knp-snappy' => 'v1.4.2@b66f79334421c26d9c244427963fa2d92980b5d3',
  'knplabs/knp-snappy-bundle' => 'v1.7.1@89a633d30d39b71b38511b70e1f0495164140933',
  'kosinix/grafika' => '2.0.8@211f61fc334b8b36616b23e8af7c5727971d96ee',
  'kriswallsmith/assetic' => 'v1.4.0@e911c437dbdf006a8f62c2f59b15b2d69a5e0aa1',
  'lexik/form-filter-bundle' => 'v5.0.10@92df0638173979dc906bda7a33a10b98429d2057',
  'liip/imagine-bundle' => '1.9.1@3084c77e984ec669e0d645250a3cb1077d8b92f6',
  'liuggio/excelbundle' => 'v2.1.0@b4fe94b64449490a1b5fbbce827c2501be335126',
  'maennchen/zipstream-php' => '2.1.0@c4c5803cc1f93df3d2448478ef79394a5981cc58',
  'markbaker/complex' => '3.0.2@95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
  'markbaker/matrix' => '3.0.1@728434227fe21be27ff6d86621a1b13107a2562c',
  'markrogoyski/math-php' => 'v0.62.0@09a38249fcb0a7199b575d65fe6ffe8141d8128c',
  'masterminds/html5' => '2.7.6@897eb517a343a2281f11bc5556d6548db7d93947',
  'meteo-concept/hcaptcha-bundle' => 'v2.4.1@1f1af87b511777b7f5adcb93f259353e48305818',
  'monolog/monolog' => '1.27.1@904713c5929655dc9b97288b69cfeedad610c9a1',
  'myclabs/php-enum' => '1.8.4@a867478eae49c9f59ece437ae7f9506bfaa27483',
  'nikic/php-parser' => 'v4.15.4@6bb5176bc4af8bcb7d926f88718db9b96a2d4290',
  'nyholm/psr7' => '1.5.1@f734364e38a876a23be4d906a2a089e1315be18a',
  'pagerfanta/pagerfanta' => 'v2.7.3@5f2aa1f1c9d1a6520f459e84b63e2bc25e9eea5b',
  'paragonie/random_compat' => 'v2.0.21@96c132c7f2f7bc3230723b66e89f8f150b29d5ae',
  'phenx/php-font-lib' => '0.5.4@dd448ad1ce34c63d09baccd05415e361300c35b4',
  'phenx/php-svg-lib' => '0.5.0@76876c6cf3080bcb6f249d7d59705108166a6685',
  'php-http/message-factory' => 'v1.0.2@a478cb11f66a6ac48d8954216cfed9aa06a501a1',
  'phpcollection/phpcollection' => '0.6.0@56d18c8c2c0400f2838703246ac7de919a605763',
  'phpmailer/phpmailer' => 'v6.8.0@df16b615e371d81fb79e506277faea67a1be18f1',
  'phpoffice/phpexcel' => '1.8.2@1441011fb7ecdd8cc689878f54f8b58a6805f870',
  'phpoffice/phpspreadsheet' => '1.25.2@a317a09e7def49852400a4b3eca4a4b0790ceeb5',
  'phpoption/phpoption' => '1.9.1@dd3a383e599f49777d8b628dadbb90cae435b87e',
  'phpseclib/phpseclib' => '2.0.42@665d289f59e646a259ebf13f29be7f6f54cab24b',
  'pimple/pimple' => 'v3.5.0@a94b3a4db7fb774b3d78dad2315ddc07629e1bed',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.1.1@8622567409010282b7aeebe4bb841fe98b58dcaf',
  'psr/http-client' => '1.0.1@2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
  'psr/http-factory' => '1.0.1@12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
  'psr/http-message' => '1.1@cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
  'psr/link' => '1.0.0@eea8e8662d5cd3ae4517c9b864493f59fca95562',
  'psr/log' => '1.1.4@d49695b909c3b7628b6289db5479a1c204601f11',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'ralouphie/getallheaders' => '3.0.3@120b605dfeb996808c31b6477290a714d356e822',
  'react/cache' => 'v0.4.2@75494f26b4ef089db9bf8c90b63c296246e099e8',
  'react/child-process' => 'v0.4.3@b81d06daaafb5d7d592b6f7f8b1b7905cdef9ac6',
  'react/dns' => 'v0.4.17@0f30c6ceb71504d359d51132a97e1703051f1589',
  'react/event-loop' => 'v0.4.3@8bde03488ee897dc6bb3d91e4e17c353f9c5252f',
  'react/http' => 'v0.4.4@aac319bd789cbc7b478d42cde2d03596e97e3222',
  'react/http-client' => 'v0.4.4@391e1e771c2255954226204edcdc5a2764938e6a',
  'react/promise' => 'v2.9.0@234f8fd1023c9158e2314fa9d7d0e6a83db42910',
  'react/promise-timer' => 'v1.6.0@daee9baf6ef30c43ea4c86399f828bb5f558f6e6',
  'react/react' => 'v0.4.2@457b6b8a16a37c11278cac0870d6d2ff911c5765',
  'react/socket' => 'v0.4.6@cf074e53c974df52388ebd09710a9018894745d2',
  'react/socket-client' => 'v0.4.6@49e730523b73d912e56f7a41f53ed3fc083ae167',
  'react/stream' => 'v0.4.6@44dc7f51ea48624110136b535b9ba44fd7d0c1ee',
  'ringcentral/psr7' => '1.3.0@360faaec4b563958b673fb52bbe94e37f14bc686',
  'sabberworm/php-css-parser' => '8.4.0@e41d2140031d533348b2192a83f02d8dd8a71d30',
  'sensio/distribution-bundle' => 'v5.0.25@80a38234bde8321fb92aa0b8c27978a272bb4baf',
  'sensio/framework-extra-bundle' => 'v3.0.29@bb907234df776b68922eb4b25bfa061683597b6a',
  'sensio/generator-bundle' => 'v3.1.7@28cbaa244bd0816fd8908b93f90380bcd7b67a65',
  'sensiolabs/security-checker' => 'v6.0.3@a576c01520d9761901f269c4934ba55448be4a54',
  'stof/doctrine-extensions-bundle' => 'v1.3.0@46db71ec7ffee9122eca3cdddd4ef8d84bae269c',
  'swiftmailer/swiftmailer' => 'v5.4.12@181b89f18a90f8925ef805f950d47a7190e9b950',
  'symfony/assetic-bundle' => 'v2.8.2@2e0a23a4874838e26de6f025e02fc63328921a4c',
  'symfony/deprecation-contracts' => 'v2.5.2@e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
  'symfony/http-client' => 'v5.4.22@4cd1b7e7ee846c8b22cb47cbc435344af9b2a8bf',
  'symfony/http-client-contracts' => 'v2.5.2@ba6a9f0e8f3edd190520ee3b9a958596b6ca2e70',
  'symfony/mime' => 'v5.4.13@bb2ccf759e2b967dcd11bdee5bdf30dddd2290bd',
  'symfony/monolog-bundle' => 'v3.6.0@e495f5c7e4e672ffef4357d4a4d85f010802f940',
  'symfony/polyfill-apcu' => 'v1.27.0@6e7f6ed2168779a2b3927e606a9768860a8bdfa0',
  'symfony/polyfill-ctype' => 'v1.27.0@5bbc823adecdae860bb64756d639ecfec17b050a',
  'symfony/polyfill-intl-icu' => 'v1.27.0@a3d9148e2c363588e05abbdd4ee4f971f0a5330c',
  'symfony/polyfill-intl-idn' => 'v1.27.0@639084e360537a19f9ee352433b84ce831f3d2da',
  'symfony/polyfill-intl-normalizer' => 'v1.27.0@19bd1e4fcd5b91116f14d8533c57831ed00571b6',
  'symfony/polyfill-mbstring' => 'v1.27.0@8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
  'symfony/polyfill-php56' => 'v1.20.0@54b8cd7e6c1643d78d011f3be89f3ef1f9f4c675',
  'symfony/polyfill-php70' => 'v1.20.0@5f03a781d984aae42cebd18e7912fa80f02ee644',
  'symfony/polyfill-php72' => 'v1.27.0@869329b1e9894268a8a61dabb69153029b7a8c97',
  'symfony/polyfill-php73' => 'v1.27.0@9e8ecb5f92152187c4799efd3c96b78ccab18ff9',
  'symfony/polyfill-php80' => 'v1.27.0@7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
  'symfony/service-contracts' => 'v2.5.2@4b426aac47d6427cc1a1d0f7e2ac724627f5966c',
  'symfony/swiftmailer-bundle' => 'v2.6.7@c4808f5169efc05567be983909d00f00521c53ec',
  'symfony/symfony' => 'v3.4.49@ba0e346e3ad11de4a307fe4fa2452a3656dcc17b',
  'symfony/translation-contracts' => 'v2.5.2@136b19dd05cdf0709db6537d058bcab6dd6e2dbe',
  'twig/extensions' => 'v1.5.4@57873c8b0c1be51caa47df2cdb824490beb16202',
  'twig/twig' => 'v2.15.4@3e059001d6d597dd50ea7c74dd2464b4adea48d3',
  'vich/uploader-bundle' => '1.8.8@759bf0e6d8ceb4bcfb066da9b2789ab3dfea0d9c',
  'white-october/pagerfanta-bundle' => 'v1.3.2@6df560869b5e09a3acf920890ab40598998b30ae',
  'willdurand/jsonp-callback-validator' => 'v1.1.0@1a7d388bb521959e612ef50c5c7b1691b097e909',
  'symfony/phpunit-bridge' => 'v4.4.49@b3378a7d305666a69e08457b65af8bca179fbbbb',
  'taste/dev' => '2.6.x-dev@ef87d46a0400a5a545e16db108aa8099131d6244',
);

    private function __construct()
    {
    }

    /**
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function rootPackageName() : string
    {
        if (!self::composer2ApiUsable()) {
            return self::ROOT_PACKAGE_NAME;
        }

        return InstalledVersions::getRootPackage()['name'];
    }

    /**
     * @throws OutOfBoundsException If a version cannot be located.
     *
     * @psalm-param key-of<self::VERSIONS> $packageName
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function getVersion(string $packageName): string
    {
        if (self::composer2ApiUsable()) {
            return InstalledVersions::getPrettyVersion($packageName)
                . '@' . InstalledVersions::getReference($packageName);
        }

        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }

    private static function composer2ApiUsable(): bool
    {
        if (!class_exists(InstalledVersions::class, false)) {
            return false;
        }

        if (method_exists(InstalledVersions::class, 'getAllRawData')) {
            $rawData = InstalledVersions::getAllRawData();
            if (count($rawData) === 1 && count($rawData[0]) === 0) {
                return false;
            }
        } else {
            $rawData = InstalledVersions::getRawData();
            if ($rawData === null || $rawData === []) {
                return false;
            }
        }

        return true;
    }
}
