<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'n3b\\Bundle\\Util\\HttpFoundation\\StreamResponse' => array($vendorDir . '/irongit/symfony2-stream-response'),
    'Twig_Extensions_' => array($vendorDir . '/twig/extensions/lib'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'PhpCollection' => array($vendorDir . '/phpcollection/phpcollection/src'),
    'PHPQRCode' => array($vendorDir . '/aferrandini/phpqrcode/lib'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Metadata\\' => array($vendorDir . '/jms/metadata/src'),
    'Kachkaev\\PHPR\\' => array($vendorDir . '/kachkaev/php-r/src'),
    'JsonpCallbackValidator' => array($vendorDir . '/willdurand/jsonp-callback-validator/src'),
    'JMS\\Serializer' => array($vendorDir . '/jms/serializer/src'),
    'JMS\\I18nRoutingBundle' => array($vendorDir . '/jms/i18n-routing-bundle'),
    'JMS\\' => array($vendorDir . '/jms/parser-lib/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Guzzle\\Parser' => array($vendorDir . '/guzzle/parser'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'CG\\' => array($vendorDir . '/jms/cg/src'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
);
