<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(
            0 => '2.6.x-dev',
        ),
        'reference' => 'ef87d46a0400a5a545e16db108aa8099131d6244',
        'name' => 'taste/dev',
        'dev' => true,
    ),
    'versions' => array(
        'aferrandini/phpqrcode' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aferrandini/phpqrcode',
            'aliases' => array(),
            'reference' => '3c1c0454d43710ab5bbe19a51ad4cb41c22e3d46',
            'dev_requirement' => false,
        ),
        'behat/transliterator' => array(
            'pretty_version' => 'v1.5.0',
            'version' => '1.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/transliterator',
            'aliases' => array(),
            'reference' => 'baac5873bac3749887d28ab68e2f74db3a4408af',
            'dev_requirement' => false,
        ),
        'chillerlan/php-qrcode' => array(
            'pretty_version' => '3.4.1',
            'version' => '3.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-qrcode',
            'aliases' => array(),
            'reference' => '468603b687a5fe75c1ff33857a45f1726c7b95a9',
            'dev_requirement' => false,
        ),
        'chillerlan/php-settings-container' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chillerlan/php-settings-container',
            'aliases' => array(),
            'reference' => 'd1b5284d6eb3a767459738bb0b20073f0cb3eeaf',
            'dev_requirement' => false,
        ),
        'cocur/slugify' => array(
            'pretty_version' => 'v2.5',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cocur/slugify',
            'aliases' => array(),
            'reference' => 'e8167e9a3236044afebd6e8ab13ebeb3ec9ca145',
            'dev_requirement' => false,
        ),
        'composer/package-versions-deprecated' => array(
            'pretty_version' => '1.11.99.5',
            'version' => '1.11.99.5',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./package-versions-deprecated',
            'aliases' => array(),
            'reference' => 'b4f54f74ef3453349c24a845d22392cd31e65f1d',
            'dev_requirement' => false,
        ),
        'deployer/deployer' => array(
            'pretty_version' => 'v4.3.4',
            'version' => '4.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../deployer/deployer',
            'aliases' => array(),
            'reference' => '8fc00d4877b7d15c385cba4cf0eef4e78c4e9b75',
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.14.3',
            'version' => '1.14.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'reference' => 'fb0d71a7393298a7b232cbf4c8b1f73f3ec3d5af',
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'reference' => '56cd022adb5514472cb144c087393c1821911d09',
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'reference' => '2b44dd4cbca8b5744327de78bafef5945c7e7b5e',
            'dev_requirement' => false,
        ),
        'doctrine/common' => array(
            'pretty_version' => '2.13.3',
            'version' => '2.13.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/common',
            'aliases' => array(),
            'reference' => 'f3812c026e557892c34ef37f6ab808a6b567da7f',
            'dev_requirement' => false,
        ),
        'doctrine/data-fixtures' => array(
            'pretty_version' => '1.5.4',
            'version' => '1.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/data-fixtures',
            'aliases' => array(),
            'reference' => 'd25660094fb25ee139aac11c7f052bea169b3f88',
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '2.13.9',
            'version' => '2.13.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'reference' => 'c480849ca3ad6706a39c970cdfe6888fa8a058b8',
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'reference' => '0e2a4f1f8cdfc7a92ec3b01c9334898c806b30de',
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-bundle' => array(
            'pretty_version' => '1.12.13',
            'version' => '1.12.13.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-bundle',
            'aliases' => array(),
            'reference' => '85460b85edd8f61a16ad311e7ffc5d255d3c937c',
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-cache-bundle' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-cache-bundle',
            'aliases' => array(),
            'reference' => '6bee2f9b339847e8a984427353670bad4e7bdccb',
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-fixtures-bundle' => array(
            'pretty_version' => 'v2.4.1',
            'version' => '2.4.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-fixtures-bundle',
            'aliases' => array(),
            'reference' => '74b8cc70a4a25b774628ee59f4cdf3623a146273',
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'reference' => '95aa4cb529f1e96576f3fda9f5705ada4056a520',
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '1.4.4',
            'version' => '1.4.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'reference' => '4bd5c1cdfcd00e9e2d8c484f79150f67e5d355d9',
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'reference' => '0a0fa9780f5d4e507415a065172d26a98d02047b',
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'reference' => 'c268e882d4dbdd85e36e4ad69e02dc284f89d229',
            'dev_requirement' => false,
        ),
        'doctrine/orm' => array(
            'pretty_version' => '2.7.5',
            'version' => '2.7.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/orm',
            'aliases' => array(),
            'reference' => '01187c9260cd085529ddd1273665217cae659640',
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '1.3.8',
            'version' => '1.3.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'reference' => '7a6eac9fb6f61bba91328f15aa7547f4806ca288',
            'dev_requirement' => false,
        ),
        'doctrine/reflection' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/reflection',
            'aliases' => array(),
            'reference' => '1034e5e71f89978b80f9c1570e7226f6c3b9b6fb',
            'dev_requirement' => false,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'reference' => 'e8d2d5e37e8b0b30f0732a011295ab80680d7e85',
            'dev_requirement' => false,
        ),
        'elfet/pure' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../elfet/pure',
            'aliases' => array(),
            'reference' => '05aa6b44cea9b0457ec1e5e67e8278cd89d47f21',
            'dev_requirement' => false,
        ),
        'evenement/evenement' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../evenement/evenement',
            'aliases' => array(),
            'reference' => '6ba9a777870ab49f417e703229d53931ed40fd7a',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.16.0',
            'version' => '4.16.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '523407fb06eb9e5f3d59889b3978d5bfe94299c8',
            'dev_requirement' => false,
        ),
        'fig/link-util' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fig/link-util',
            'aliases' => array(),
            'reference' => '5d7b8d04ed3393b4b59968ca1e906fb7186d81e8',
            'dev_requirement' => false,
        ),
        'fresh/vich-uploader-serialization-bundle' => array(
            'pretty_version' => 'v2.4.3',
            'version' => '2.4.3.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../fresh/vich-uploader-serialization-bundle',
            'aliases' => array(),
            'reference' => '21d988723c39bd6384865ca5c764a4446cedbcbc',
            'dev_requirement' => false,
        ),
        'friendsofsymfony/jsrouting-bundle' => array(
            'pretty_version' => '1.6.3',
            'version' => '1.6.3.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../friendsofsymfony/jsrouting-bundle',
            'aliases' => array(),
            'reference' => '49c1069132dcef371fb526351569deabeb6f0d8e',
            'dev_requirement' => false,
        ),
        'friendsofsymfony/user-bundle' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../friendsofsymfony/user-bundle',
            'aliases' => array(),
            'reference' => '2fc8a023d7ab482321cf7ec810ed49eab40eb50f',
            'dev_requirement' => false,
        ),
        'gedmo/doctrine-extensions' => array(
            'pretty_version' => 'v2.4.42',
            'version' => '2.4.42.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gedmo/doctrine-extensions',
            'aliases' => array(),
            'reference' => 'b6c4442b4f32ce05673fbdf1fa4a2d5e315cc0a4',
            'dev_requirement' => false,
        ),
        'gregwar/captcha' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gregwar/captcha',
            'aliases' => array(),
            'reference' => '6e5b61b66ac89885b505153f4ef9a74ffa5b3074',
            'dev_requirement' => false,
        ),
        'gregwar/captcha-bundle' => array(
            'pretty_version' => 'v2.0.7',
            'version' => '2.0.7.0',
            'type' => 'captcha-bundle',
            'install_path' => __DIR__ . '/../gregwar/captcha-bundle',
            'aliases' => array(),
            'reference' => '3ccfdf1c9324acbdfbcccea2c454075115741b3a',
            'dev_requirement' => false,
        ),
        'guzzle/parser' => array(
            'pretty_version' => 'v3.9.2',
            'version' => '3.9.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzle/parser/Guzzle/Parser',
            'aliases' => array(),
            'reference' => '6874d171318a8e93eb6d224cf85e4678490b625c',
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.5.0',
            'version' => '7.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => 'b50a2a1251152e43f6a37f0fa053e730a67d25ba',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.2',
            'version' => '1.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'b94b2807d85443f9719887892882d0329d1e2598',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.4.4',
            'version' => '2.4.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => '3cf1b6d4f0c820a2cf8bcaec39fc698f3443b5cf',
            'dev_requirement' => false,
        ),
        'imagine/imagine' => array(
            'pretty_version' => 'v0.7.1',
            'version' => '0.7.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../imagine/imagine',
            'aliases' => array(),
            'reference' => 'a9a702a946073cbca166718f1b02a1e72d742daa',
            'dev_requirement' => false,
        ),
        'incenteev/composer-parameter-handler' => array(
            'pretty_version' => 'v2.1.5',
            'version' => '2.1.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../incenteev/composer-parameter-handler',
            'aliases' => array(),
            'reference' => 'e1dd118763503f7fd766f907013e1d76d525fcc4',
            'dev_requirement' => false,
        ),
        'ip/slugify-namer' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ip/slugify-namer',
            'aliases' => array(),
            'reference' => 'd7b46fc7ed897216d6a8e7b1e7c0ca158c60bbc1',
            'dev_requirement' => false,
        ),
        'irongit/symfony2-stream-response' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../irongit/symfony2-stream-response/n3b/Bundle/Util/HttpFoundation/StreamResponse',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '3e5082e7beec9c9130e30e49bad44e1e99ab33b1',
            'dev_requirement' => false,
        ),
        'jdorn/sql-formatter' => array(
            'pretty_version' => 'v1.2.17',
            'version' => '1.2.17.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jdorn/sql-formatter',
            'aliases' => array(),
            'reference' => '64990d96e0959dff8e059dfcdc1af130728d92bc',
            'dev_requirement' => false,
        ),
        'jms/aop-bundle' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../jms/aop-bundle',
            'aliases' => array(),
            'reference' => '4ee2089a81b54ce94a8c94e95b48d5bb353dd8d0',
            'dev_requirement' => false,
        ),
        'jms/cg' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jms/cg',
            'aliases' => array(),
            'reference' => '2152ea2c48f746a676debb841644ae64cae27835',
            'dev_requirement' => false,
        ),
        'jms/di-extra-bundle' => array(
            'pretty_version' => '1.9.2',
            'version' => '1.9.2.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../jms/di-extra-bundle',
            'aliases' => array(),
            'reference' => 'fa82a4e6c9dc84df8015805028575217c0be4a54',
            'dev_requirement' => false,
        ),
        'jms/i18n-routing-bundle' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../jms/i18n-routing-bundle/JMS/I18nRoutingBundle',
            'aliases' => array(),
            'reference' => '052917faa3f00801c288f6d475ef7e2485928d5b',
            'dev_requirement' => false,
        ),
        'jms/metadata' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jms/metadata',
            'aliases' => array(),
            'reference' => 'e5854ab1aa643623dc64adde718a8eec32b957a8',
            'dev_requirement' => false,
        ),
        'jms/parser-lib' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jms/parser-lib',
            'aliases' => array(),
            'reference' => '4f45952f9fa97d67adc5dd69e7d622fc89a7675d',
            'dev_requirement' => false,
        ),
        'jms/serializer' => array(
            'pretty_version' => '1.14.1',
            'version' => '1.14.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jms/serializer',
            'aliases' => array(),
            'reference' => 'ba908d278fff27ec01fb4349f372634ffcd697c0',
            'dev_requirement' => false,
        ),
        'jms/serializer-bundle' => array(
            'pretty_version' => '2.4.4',
            'version' => '2.4.4.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../jms/serializer-bundle',
            'aliases' => array(),
            'reference' => '92ee808c64c1c180775a0e57d00e3be0674668fb',
            'dev_requirement' => false,
        ),
        'jms/translation-bundle' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../jms/translation-bundle',
            'aliases' => array(),
            'reference' => '153f4c9892bd6481eebd42c5da56666c8d0fa7ce',
            'dev_requirement' => false,
        ),
        'kachkaev/php-r' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kachkaev/php-r',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => '8aa5bb42e6042cef1a4ab12b63782f4d17ce0f1d',
            'dev_requirement' => false,
        ),
        'knplabs/knp-menu' => array(
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../knplabs/knp-menu',
            'aliases' => array(),
            'reference' => '56ffccc3ed8f7b69ec6e6d587e9f840c0a270739',
            'dev_requirement' => false,
        ),
        'knplabs/knp-menu-bundle' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../knplabs/knp-menu-bundle',
            'aliases' => array(),
            'reference' => '78b0cebf8e1490f12ba6555511282954de83f627',
            'dev_requirement' => false,
        ),
        'knplabs/knp-snappy' => array(
            'pretty_version' => 'v1.4.2',
            'version' => '1.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../knplabs/knp-snappy',
            'aliases' => array(),
            'reference' => 'b66f79334421c26d9c244427963fa2d92980b5d3',
            'dev_requirement' => false,
        ),
        'knplabs/knp-snappy-bundle' => array(
            'pretty_version' => 'v1.7.1',
            'version' => '1.7.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../knplabs/knp-snappy-bundle',
            'aliases' => array(),
            'reference' => '89a633d30d39b71b38511b70e1f0495164140933',
            'dev_requirement' => false,
        ),
        'kosinix/grafika' => array(
            'pretty_version' => '2.0.8',
            'version' => '2.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kosinix/grafika',
            'aliases' => array(),
            'reference' => '211f61fc334b8b36616b23e8af7c5727971d96ee',
            'dev_requirement' => false,
        ),
        'kriswallsmith/assetic' => array(
            'pretty_version' => 'v1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kriswallsmith/assetic',
            'aliases' => array(),
            'reference' => 'e911c437dbdf006a8f62c2f59b15b2d69a5e0aa1',
            'dev_requirement' => false,
        ),
        'lexik/form-filter-bundle' => array(
            'pretty_version' => 'v5.0.10',
            'version' => '5.0.10.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../lexik/form-filter-bundle',
            'aliases' => array(),
            'reference' => '92df0638173979dc906bda7a33a10b98429d2057',
            'dev_requirement' => false,
        ),
        'liip/imagine-bundle' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../liip/imagine-bundle',
            'aliases' => array(),
            'reference' => '3084c77e984ec669e0d645250a3cb1077d8b92f6',
            'dev_requirement' => false,
        ),
        'liuggio/excelbundle' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../liuggio/excelbundle',
            'aliases' => array(),
            'reference' => 'b4fe94b64449490a1b5fbbce827c2501be335126',
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'reference' => 'c4c5803cc1f93df3d2448478ef79394a5981cc58',
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'reference' => '95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'reference' => '728434227fe21be27ff6d86621a1b13107a2562c',
            'dev_requirement' => false,
        ),
        'markrogoyski/math-php' => array(
            'pretty_version' => 'v0.62.0',
            'version' => '0.62.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markrogoyski/math-php',
            'aliases' => array(),
            'reference' => '09a38249fcb0a7199b575d65fe6ffe8141d8128c',
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.7.6',
            'version' => '2.7.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'reference' => '897eb517a343a2281f11bc5556d6548db7d93947',
            'dev_requirement' => false,
        ),
        'meteo-concept/hcaptcha-bundle' => array(
            'pretty_version' => 'v2.4.1',
            'version' => '2.4.1.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../meteo-concept/hcaptcha-bundle',
            'aliases' => array(),
            'reference' => '1f1af87b511777b7f5adcb93f259353e48305818',
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '1.27.1',
            'version' => '1.27.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'reference' => '904713c5929655dc9b97288b69cfeedad610c9a1',
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.4',
            'version' => '1.8.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'reference' => 'a867478eae49c9f59ece437ae7f9506bfaa27483',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.15.4',
            'version' => '4.15.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '6bb5176bc4af8bcb7d926f88718db9b96a2d4290',
            'dev_requirement' => false,
        ),
        'nyholm/psr7' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nyholm/psr7',
            'aliases' => array(),
            'reference' => 'f734364e38a876a23be4d906a2a089e1315be18a',
            'dev_requirement' => false,
        ),
        'ocramius/package-versions' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.11.99',
            ),
        ),
        'pagerfanta/core' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v2.7.3',
            ),
        ),
        'pagerfanta/doctrine-collections-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v2.7.3',
            ),
        ),
        'pagerfanta/doctrine-dbal-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v2.7.3',
            ),
        ),
        'pagerfanta/doctrine-mongodb-odm-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v2.7.3',
            ),
        ),
        'pagerfanta/doctrine-orm-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v2.7.3',
            ),
        ),
        'pagerfanta/doctrine-phpcr-odm-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v2.7.3',
            ),
        ),
        'pagerfanta/elastica-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v2.7.3',
            ),
        ),
        'pagerfanta/pagerfanta' => array(
            'pretty_version' => 'v2.7.3',
            'version' => '2.7.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pagerfanta/pagerfanta',
            'aliases' => array(),
            'reference' => '5f2aa1f1c9d1a6520f459e84b63e2bc25e9eea5b',
            'dev_requirement' => false,
        ),
        'pagerfanta/solarium-adapter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v2.7.3',
            ),
        ),
        'pagerfanta/twig' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v2.7.3',
            ),
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v2.0.21',
            'version' => '2.0.21.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '96c132c7f2f7bc3230723b66e89f8f150b29d5ae',
            'dev_requirement' => false,
        ),
        'phenx/php-font-lib' => array(
            'pretty_version' => '0.5.4',
            'version' => '0.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-font-lib',
            'aliases' => array(),
            'reference' => 'dd448ad1ce34c63d09baccd05415e361300c35b4',
            'dev_requirement' => false,
        ),
        'phenx/php-svg-lib' => array(
            'pretty_version' => '0.5.0',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-svg-lib',
            'aliases' => array(),
            'reference' => '76876c6cf3080bcb6f249d7d59705108166a6685',
            'dev_requirement' => false,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/message-factory' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(),
            'reference' => 'a478cb11f66a6ac48d8954216cfed9aa06a501a1',
            'dev_requirement' => false,
        ),
        'phpcollection/phpcollection' => array(
            'pretty_version' => '0.6.0',
            'version' => '0.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpcollection/phpcollection',
            'aliases' => array(),
            'reference' => '56d18c8c2c0400f2838703246ac7de919a605763',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.8.0',
            'version' => '6.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'df16b615e371d81fb79e506277faea67a1be18f1',
            'dev_requirement' => false,
        ),
        'phpoffice/phpexcel' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpexcel',
            'aliases' => array(),
            'reference' => '1441011fb7ecdd8cc689878f54f8b58a6805f870',
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.25.2',
            'version' => '1.25.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'reference' => 'a317a09e7def49852400a4b3eca4a4b0790ceeb5',
            'dev_requirement' => false,
        ),
        'phpoption/phpoption' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoption/phpoption',
            'aliases' => array(),
            'reference' => 'dd3a383e599f49777d8b628dadbb90cae435b87e',
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.42',
            'version' => '2.0.42.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => '665d289f59e646a259ebf13f29be7f6f54cab24b',
            'dev_requirement' => false,
        ),
        'pimple/pimple' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimple/pimple',
            'aliases' => array(),
            'reference' => 'a94b3a4db7fb774b3d78dad2315ddc07629e1bed',
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '8622567409010282b7aeebe4bb841fe98b58dcaf',
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/link' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/link',
            'aliases' => array(),
            'reference' => 'eea8e8662d5cd3ae4517c9b864493f59fca95562',
            'dev_requirement' => false,
        ),
        'psr/link-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'react/cache' => array(
            'pretty_version' => 'v0.4.2',
            'version' => '0.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/cache',
            'aliases' => array(),
            'reference' => '75494f26b4ef089db9bf8c90b63c296246e099e8',
            'dev_requirement' => false,
        ),
        'react/child-process' => array(
            'pretty_version' => 'v0.4.3',
            'version' => '0.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/child-process',
            'aliases' => array(),
            'reference' => 'b81d06daaafb5d7d592b6f7f8b1b7905cdef9ac6',
            'dev_requirement' => false,
        ),
        'react/dns' => array(
            'pretty_version' => 'v0.4.17',
            'version' => '0.4.17.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/dns',
            'aliases' => array(),
            'reference' => '0f30c6ceb71504d359d51132a97e1703051f1589',
            'dev_requirement' => false,
        ),
        'react/event-loop' => array(
            'pretty_version' => 'v0.4.3',
            'version' => '0.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/event-loop',
            'aliases' => array(),
            'reference' => '8bde03488ee897dc6bb3d91e4e17c353f9c5252f',
            'dev_requirement' => false,
        ),
        'react/http' => array(
            'pretty_version' => 'v0.4.4',
            'version' => '0.4.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/http',
            'aliases' => array(),
            'reference' => 'aac319bd789cbc7b478d42cde2d03596e97e3222',
            'dev_requirement' => false,
        ),
        'react/http-client' => array(
            'pretty_version' => 'v0.4.4',
            'version' => '0.4.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/http-client',
            'aliases' => array(),
            'reference' => '391e1e771c2255954226204edcdc5a2764938e6a',
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.9.0',
            'version' => '2.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'reference' => '234f8fd1023c9158e2314fa9d7d0e6a83db42910',
            'dev_requirement' => false,
        ),
        'react/promise-timer' => array(
            'pretty_version' => 'v1.6.0',
            'version' => '1.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise-timer',
            'aliases' => array(),
            'reference' => 'daee9baf6ef30c43ea4c86399f828bb5f558f6e6',
            'dev_requirement' => false,
        ),
        'react/react' => array(
            'pretty_version' => 'v0.4.2',
            'version' => '0.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/react',
            'aliases' => array(),
            'reference' => '457b6b8a16a37c11278cac0870d6d2ff911c5765',
            'dev_requirement' => false,
        ),
        'react/socket' => array(
            'pretty_version' => 'v0.4.6',
            'version' => '0.4.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/socket',
            'aliases' => array(),
            'reference' => 'cf074e53c974df52388ebd09710a9018894745d2',
            'dev_requirement' => false,
        ),
        'react/socket-client' => array(
            'pretty_version' => 'v0.4.6',
            'version' => '0.4.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/socket-client',
            'aliases' => array(),
            'reference' => '49e730523b73d912e56f7a41f53ed3fc083ae167',
            'dev_requirement' => false,
        ),
        'react/stream' => array(
            'pretty_version' => 'v0.4.6',
            'version' => '0.4.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/stream',
            'aliases' => array(),
            'reference' => '44dc7f51ea48624110136b535b9ba44fd7d0c1ee',
            'dev_requirement' => false,
        ),
        'ringcentral/psr7' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ringcentral/psr7',
            'aliases' => array(),
            'reference' => '360faaec4b563958b673fb52bbe94e37f14bc686',
            'dev_requirement' => false,
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => '8.4.0',
            'version' => '8.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'reference' => 'e41d2140031d533348b2192a83f02d8dd8a71d30',
            'dev_requirement' => false,
        ),
        'sensio/distribution-bundle' => array(
            'pretty_version' => 'v5.0.25',
            'version' => '5.0.25.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../sensio/distribution-bundle',
            'aliases' => array(),
            'reference' => '80a38234bde8321fb92aa0b8c27978a272bb4baf',
            'dev_requirement' => false,
        ),
        'sensio/framework-extra-bundle' => array(
            'pretty_version' => 'v3.0.29',
            'version' => '3.0.29.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../sensio/framework-extra-bundle',
            'aliases' => array(),
            'reference' => 'bb907234df776b68922eb4b25bfa061683597b6a',
            'dev_requirement' => false,
        ),
        'sensio/generator-bundle' => array(
            'pretty_version' => 'v3.1.7',
            'version' => '3.1.7.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../sensio/generator-bundle',
            'aliases' => array(),
            'reference' => '28cbaa244bd0816fd8908b93f90380bcd7b67a65',
            'dev_requirement' => false,
        ),
        'sensiolabs/security-checker' => array(
            'pretty_version' => 'v6.0.3',
            'version' => '6.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sensiolabs/security-checker',
            'aliases' => array(),
            'reference' => 'a576c01520d9761901f269c4934ba55448be4a54',
            'dev_requirement' => false,
        ),
        'stof/doctrine-extensions-bundle' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../stof/doctrine-extensions-bundle',
            'aliases' => array(),
            'reference' => '46db71ec7ffee9122eca3cdddd4ef8d84bae269c',
            'dev_requirement' => false,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v5.4.12',
            'version' => '5.4.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'reference' => '181b89f18a90f8925ef805f950d47a7190e9b950',
            'dev_requirement' => false,
        ),
        'symfony/asset' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/assetic-bundle' => array(
            'pretty_version' => 'v2.8.2',
            'version' => '2.8.2.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/assetic-bundle',
            'aliases' => array(),
            'reference' => '2e0a23a4874838e26de6f025e02fc63328921a4c',
            'dev_requirement' => false,
        ),
        'symfony/browser-kit' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/class-loader' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/css-selector' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/debug' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/debug-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/dependency-injection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'dev_requirement' => false,
        ),
        'symfony/doctrine-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/dom-crawler' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/dotenv' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/event-dispatcher' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/expression-language' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/finder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/form' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/framework-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/http-client' => array(
            'pretty_version' => 'v5.4.22',
            'version' => '5.4.22.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client',
            'aliases' => array(),
            'reference' => '4cd1b7e7ee846c8b22cb47cbc435344af9b2a8bf',
            'dev_requirement' => false,
        ),
        'symfony/http-client-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client-contracts',
            'aliases' => array(),
            'reference' => 'ba6a9f0e8f3edd190520ee3b9a958596b6ca2e70',
            'dev_requirement' => false,
        ),
        'symfony/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.4',
            ),
        ),
        'symfony/http-foundation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/http-kernel' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/inflector' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/intl' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/ldap' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/lock' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v5.4.13',
            'version' => '5.4.13.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'reference' => 'bb2ccf759e2b967dcd11bdee5bdf30dddd2290bd',
            'dev_requirement' => false,
        ),
        'symfony/monolog-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/monolog-bundle' => array(
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/monolog-bundle',
            'aliases' => array(),
            'reference' => 'e495f5c7e4e672ffef4357d4a4d85f010802f940',
            'dev_requirement' => false,
        ),
        'symfony/options-resolver' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/phpunit-bridge' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/phpunit-bridge',
            'aliases' => array(),
            'reference' => 'b3378a7d305666a69e08457b65af8bca179fbbbb',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-apcu' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-apcu',
            'aliases' => array(),
            'reference' => '6e7f6ed2168779a2b3927e606a9768860a8bdfa0',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => '5bbc823adecdae860bb64756d639ecfec17b050a',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-icu' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-icu',
            'aliases' => array(),
            'reference' => 'a3d9148e2c363588e05abbdd4ee4f971f0a5330c',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '639084e360537a19f9ee352433b84ce831f3d2da',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '19bd1e4fcd5b91116f14d8533c57831ed00571b6',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php56' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'reference' => '54b8cd7e6c1643d78d011f3be89f3ef1f9f4c675',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php70' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'reference' => '5f03a781d984aae42cebd18e7912fa80f02ee644',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => '869329b1e9894268a8a61dabb69153029b7a8c97',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => '9e8ecb5f92152187c4799efd3c96b78ccab18ff9',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/property-access' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/property-info' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/proxy-manager-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/routing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/security' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/security-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/security-core' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/security-csrf' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/security-guard' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/security-http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/serializer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'reference' => '4b426aac47d6427cc1a1d0f7e2ac724627f5966c',
            'dev_requirement' => false,
        ),
        'symfony/stopwatch' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/swiftmailer-bundle' => array(
            'pretty_version' => 'v2.6.7',
            'version' => '2.6.7.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/swiftmailer-bundle',
            'aliases' => array(),
            'reference' => 'c4808f5169efc05567be983909d00f00521c53ec',
            'dev_requirement' => false,
        ),
        'symfony/symfony' => array(
            'pretty_version' => 'v3.4.49',
            'version' => '3.4.49.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/symfony',
            'aliases' => array(),
            'reference' => 'ba0e346e3ad11de4a307fe4fa2452a3656dcc17b',
            'dev_requirement' => false,
        ),
        'symfony/templating' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'reference' => '136b19dd05cdf0709db6537d058bcab6dd6e2dbe',
            'dev_requirement' => false,
        ),
        'symfony/twig-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/twig-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/validator' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/var-dumper' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/web-link' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/web-profiler-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/web-server-bundle' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/workflow' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'symfony/yaml' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.4.49',
            ),
        ),
        'taste/dev' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(
                0 => '2.6.x-dev',
            ),
            'reference' => 'ef87d46a0400a5a545e16db108aa8099131d6244',
            'dev_requirement' => false,
        ),
        'twig/extensions' => array(
            'pretty_version' => 'v1.5.4',
            'version' => '1.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/extensions',
            'aliases' => array(),
            'reference' => '57873c8b0c1be51caa47df2cdb824490beb16202',
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v2.15.4',
            'version' => '2.15.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'reference' => '3e059001d6d597dd50ea7c74dd2464b4adea48d3',
            'dev_requirement' => false,
        ),
        'vich/uploader-bundle' => array(
            'pretty_version' => '1.8.8',
            'version' => '1.8.8.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../vich/uploader-bundle',
            'aliases' => array(),
            'reference' => '759bf0e6d8ceb4bcfb066da9b2789ab3dfea0d9c',
            'dev_requirement' => false,
        ),
        'white-october/pagerfanta-bundle' => array(
            'pretty_version' => 'v1.3.2',
            'version' => '1.3.2.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../white-october/pagerfanta-bundle',
            'aliases' => array(),
            'reference' => '6df560869b5e09a3acf920890ab40598998b30ae',
            'dev_requirement' => false,
        ),
        'willdurand/jsonp-callback-validator' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/jsonp-callback-validator',
            'aliases' => array(),
            'reference' => '1a7d388bb521959e612ef50c5c7b1691b097e909',
            'dev_requirement' => false,
        ),
    ),
);
